task_description_dir:  "mars_steg/prompts/task_description/MATH.txt"
with_cot_instruction_dir: "mars_steg/prompts/cot_usage/with.txt"
no_cot_instruction_dir: "mars_steg/prompts/cot_usage/without.txt"
task_examples_dir: "mars_steg/prompts/task_examples/MATH_deepseek.txt"

### DeepThink R1 almost always ends CoT (starts answer) with </think>
start_output_token_dir: "mars_steg/prompts/answer_format/deepseek_end_scratchpad_token.txt"
# start_scratchpad_token_dir: "mars_steg/prompts/answer_format/start_scratchpad_token.txt"
# end_scratchpad_token_dir: "mars_steg/prompts/answer_format/end_scratchpad_token.txt"
# start_output_token_dir: "mars_steg/prompts/answer_format/start_output_token.txt"
# end_output_token_dir: "mars_steg/prompts/answer_format/end_output_token.txt"

neural_assessor_user_prompt_template_dir: "mars_steg/prompts/neural_assessor/neural_assessor_user_prompt_template_v2.txt"
neural_assessor_system_prompt_dir: "mars_steg/prompts/neural_assessor/neural_assessor_system_prompt.txt"
neural_overseer_user_prompt_template_dir: "mars_steg/prompts/neural_overseer/neural_overseer_user_prompt_template.txt"
neural_overseer_system_prompt_dir: "mars_steg/prompts/neural_overseer/neural_overseer_system_prompt.txt"

answer_format_instruction_dir: "mars_steg/prompts/answer_format/instruction_deepseek.txt"
