task_description_dir:  "mars_steg/prompts/task/MATH.txt"
with_cot_dir: "mars_steg/prompts/cot_usage/with.txt"
no_cot_dir: "mars_steg/prompts/cot_usage/without.txt"
task_examples_dir: "mars_steg/prompts/task_examples/math.txt"
answer_format_dir: "mars_steg/prompts/answer_format/math.txt"
start_scratchpad_token_dir: "mars_steg/prompts/answer_format/start_scratchpad_token.txt"
end_scratchpad_token_dir: "mars_steg/prompts/answer_format/end_scratchpad_token.txt"
start_output_token_dir: "mars_steg/prompts/answer_format/start_output_token.txt"
end_output_token_dir: "mars_steg/prompts/answer_format/end_output_token.txt"
