_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 84
                - 98
            "3":
                - 14
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.3
            "6": 4.47.1
            "8":
                - 5
            "12": 0.19.3
            "13": linux-x86_64
adap_kl_ctrl:
    value: true
backward_batch_size:
    value: 1
batch_size:
    value: 1
cliprange:
    value: 0.2
cliprange_value:
    value: 0.2
compare_steps:
    value: 1
dataset_num_proc:
    value: null
early_stopping:
    value: false
exp_name:
    value: train_dataset_task
forward_batch_size:
    value: null
gamma:
    value: 1
global_backward_batch_size:
    value: null
global_batch_size:
    value: null
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
horizon:
    value: 10000
init_kl_coef:
    value: 0.2
is_encoder_decoder:
    value: null
is_peft_model:
    value: null
kl_penalty:
    value: kl
lam:
    value: 0.95
learning_rate:
    value: 2.94e-05
log_with:
    value: null
max_grad_norm:
    value: null
mini_batch_size:
    value: 1
model_name:
    value: meta-llama/Llama-3.1-8B-Instruct
optimize_cuda_cache:
    value: null
optimize_device_cache:
    value: false
ppo_epochs:
    value: 100
query_dataset:
    value: stanfordnlp/imdb
ratio_threshold:
    value: 10
remove_unused_columns:
    value: true
reward_model:
    value: sentiment-analysis:lvwerra/distilbert-imdb
score_clip:
    value: null
seed:
    value: 0
steps:
    value: 20000
target:
    value: 6
target_kl:
    value: 1
task_name:
    value: null
total_ppo_epochs:
    value: 20000
tracker_project_name:
    value: trl
use_score_norm:
    value: false
use_score_scaling:
    value: false
vf_coef:
    value: 0.1
whiten_rewards:
    value: false
world_size:
    value: null
